### ISSUE TITLE
No output in the terminal

### ISSUE THREAD

**Issue by 9Mad-Max5** [radujica/tospotify#13]
Even with --verbose active and everything setup there is no Output in the Terminal.
It just does nothing. Everything is set up as explained but the Terminal stays empty. 

I think it is related to the redirect with locahost:8888.
Im running on a qnap nas directly in the admin terminal..

**Comment by radujica** [comment]
Hi @9Mad-Max5 is this issue still relevant?

It indeed sounds like a redirect problem or perhaps a stdout issue. For the latter, could try `python -u` to avoid output buffering.

**Comment by 9Mad-Max5** [comment]
It's a while back maybe I will retry it someday.

**Comment by radujica** [comment]
Closing for now
