### ISSUE TITLE
Could not determine file extension // Illegal redirect_uri

### ISSUE THREAD

**Issue by Corenail** [radujica/tospotify#19]
**Hi, I tried to use the tool, did the required steps:**

set SPOTIPY_CLIENT_ID="my client id"
set SPOTIPY_CLIENT_SECRET="my client secret"
set SPOTIPY_REDIRECT_URI="http://localhost:8888/callback/"

**And also whitelisted the url:** 
![image](https://user-images.githubusercontent.com/42466872/233870301-cfb0b454-b0ac-4a38-94c3-6f642543e1de.png)

**But when I try this code:**

python -m tospotify "11153396121" "C:/Users/Desktop/playlist.m3u8"

**It opens this page:**

https://accounts.spotify.com/authorize?client_id=%22c0006d10eb15490e9c0b37df306b3afc%22&response_type=code&redirect_uri=%22http%3A%2F%2Flocalhost%3A8888%2Fcallback%2F%22&scope=playlist-modify-private

**And says:**

Illegal redirect_uri

_**And after that it asks me to copy paste the url that I got and i get into a loop.**_

**And if I try this one:**

tospotify [-h] [--verbose] [--public] [--convert] [--playlist-id 4BcjgCsCGScaUO3RMNm7lA] "11153396121" "C:\Users\user\Desktop\playlist.m3u8"

**I get the following message:**

C:\Users\user>tospotify [-h] [--verbose] [--public] [--convert] [--playlist-id 4BcjgCsCGScaUO3RMNm7lA] "11153396121" "C:\Users\user\Desktop\playlist.m3u8"
usage: tospotify [-h] [--verbose] [--public] [--convert] [--playlist-id PLAYLIST_ID] spotify_username playlist_path
tospotify: error: argument playlist_path: Could not determine file extension

**What can I do to import my 1600 piece playlist to spotify?**

**Comment by radujica** [comment]
Hi, a few thoughts from just reading this before I can find some time to try it out on my PC:

- could you try a redirect URI without the last slash? so `set SPOTIPY_REDIRECT_URI="http://localhost:8888/callback"`
- maybe just a formatting thing in the issue description, but the square `[]` brackets for the options signify that those options are optional, so e.g. to specify the playlist id, the command would be: `tospotify --playlist-id 4BcjgCsCGScaUO3RMNm7lA "11153396121" "C:\Users\user\Desktop\playlist.m3u8"`

Let me know if these work :)
