### ISSUE TITLE
Illegal redirect_uri

### ISSUE THREAD

**Issue by Vzoromil** [radujica/tospotify#6]
Sorry if it is my fault, it is the first time I am using Python... But I always get the following error "Illegal redirect_uri".  I am using 
 the default redirect uri: http://localhost:8888/. What can be wrong?
Thank you very much!

**Comment by radujica** [comment]
I have just retried running this and it still works for me. Can you post the full error?

Do note that as mentioned in the README, you need to add the (same) redirect UI both in 
1) `https://developer.spotify.com/` settings of your app and,
2) locally as an environment variable `SPOTIPY_REDIRECT_URI`

**Comment by radujica** [comment]
Closing due to no reply; do re-open if necessary!
